logging:
  level: DEBUG
  loggers:
    io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper: DEBUG
database:
  driverClass: com.mysql.jdbc.Driver
  user: ooluroo
  password: ooluroo
  url: jdbc:mysql://localhost:3306/ooluroochallenge_test